# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/deepin-session-ui.spec

# add or remove files that should be synced
synced_files:
    - rpm/deepin-session-ui.spec
    - .packit.yaml

upstream_package_name: dde-session-ui
# downstream (Fedora) RPM package name
downstream_package_name: deepin-session-ui

actions:
  fix-spec-file: |
    bash -c "sed -i -r \"s/Version:(\s*)\S*/Version:\1${PACKIT_PROJECT_VERSION}/\" rpm/deepin-session-ui.spec"
  post-upstream-clone: |
    cp rpm/dde-session-ui.spec rpm/deepin-session-ui.spec
